#!/usr/bin/env bash
set -euo pipefail

# Copy SSH key
if [[ -f /tmp/pubkey/authorized_keys ]]; then
  cp /tmp/pubkey/authorized_keys /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
fi

# Get workspace info from environment (passed by create.sh)
WORKSPACE_PATH="${WORKSPACE_PATH:-/workspace}"
CONTAINER_NAME="${CONTAINER_NAME:-unknown}"
CLAUDE_AUTH_TYPE="${CLAUDE_AUTH_TYPE:-unknown}"

# Write MOTD
cat > /etc/motd <<MOTD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Container: ${CONTAINER_NAME}
  Profile:   claude
  Tool:      Claude Code
  Backend:   Claude API (${CLAUDE_AUTH_TYPE})
MOTD

if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo "  Workspaces:" >> /etc/motd
  IFS=',' read -ra WS_PATHS <<< "$WORKSPACE_PATH"
  for ws in "${WS_PATHS[@]}"; do
    echo "    /workspace/$(basename "$ws")" >> /etc/motd
  done
  WORKSPACE_NAME="$CONTAINER_NAME"
else
  echo "  Workspace: ${WORKSPACE_PATH}" >> /etc/motd
  WORKSPACE_NAME=$(basename "$WORKSPACE_PATH")
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >> /etc/motd

# Configure PS1 to show workspace
echo "export PS1='[\u@${WORKSPACE_NAME}:\w]\\$ '" >> /root/.bashrc
if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo 'cd /workspace' >> /root/.bashrc
else
  echo "cd /workspace/${WORKSPACE_NAME}" >> /root/.bashrc
fi

# Export user-provided environment variables for SSH sessions
# Write all non-system env vars to a file that gets sourced on login
cat > /root/.container_env <<'EOF'
# User-provided environment variables from container-dev env files
# Auto-generated by entrypoint.sh - do not edit manually
EOF

# Export ALL environment variables except system/container internals
# This captures everything from ~/.config/container-dev/env and profile .env files
while IFS='=' read -r -d '' var value; do
  # Skip internal variables set by container runtime and start.sh.
  # NOTE: auth vars (CLAUDE_AUTH_TYPE, ANTHROPIC_VERTEX_PROJECT_ID,
  # CLOUD_ML_REGION, ANTHROPIC_API_KEY) are intentionally NOT skipped — sshd
  # scrubs the container-run environment, so interactive login shells (and
  # `claude` launched from them) only see what we persist here. Without these,
  # Vertex is enabled with no project ID and auth silently fails.
  case "$var" in
    WORKSPACE_PATH|CONTAINER_NAME)
      continue ;;
    HOME|PATH|PWD|SHLVL|TERM|HOSTNAME|_)
      continue ;;
    *)
      echo "export ${var}='${value}'" >> /root/.container_env
      ;;
  esac
done < <(env -0)

echo 'source /root/.container_env 2>/dev/null || true' >> /root/.bashrc

# Claude Code settings come from the host config DIRECTORY, bind-mounted
# read-only at /tmp/claude-host by create.sh (a directory mount is used instead
# of a single-file mount so host-side edits — which replace the file inode —
# don't break the mount). We derive the container's settings from it:
#   - model / theme / model-alias pins: copied into /root/.claude/settings.json
#     (writable) so Claude Code reads them (and can apply per-repo
#     settings.local.json overrides on top).
#   - effort: Claude Code holds effort at the model default and does NOT reliably
#     apply `effortLevel` from settings.json, so it is exported as
#     CLAUDE_CODE_EFFORT_LEVEL (the highest-precedence effort control).
#   - auth wiring (CLAUDE_CODE_USE_VERTEX, ANTHROPIC_VERTEX_PROJECT_ID,
#     CLOUD_ML_REGION, ANTHROPIC_API_KEY) arrives as OS env vars from create.sh.
# Both the copy and the export run again on every interactive login, so editing
# the host file takes effect on the next `claude` launch — no recreate needed.
#
# NOTE: use `cat >dest`, not `cp`. The base /root/.bashrc aliases `cp` to
# `cp -i`, so a `cp` in the login hook becomes an interactive prompt that reads
# from the TTY and hangs the SSH login until the user presses Enter. `cat` takes
# no stdin (it reads the file argument) and ignores aliases.
mkdir -p /root/.claude
if [[ -f /tmp/claude-host/settings.json ]]; then
  cat /tmp/claude-host/settings.json > /root/.claude/settings.json 2>/dev/null || true
fi
cat >> /root/.bashrc <<'BASHRC'
if [[ -f /tmp/claude-host/settings.json ]]; then
  cat /tmp/claude-host/settings.json > /root/.claude/settings.json 2>/dev/null || true
  export CLAUDE_CODE_EFFORT_LEVEL="$(jq -r '.effortLevel // empty' /tmp/claude-host/settings.json 2>/dev/null)"
fi
BASHRC

# ---------------------------------------------------------------------------
# Auto-install the baked-in Claude Code VS Code extension
#
# VS Code Server (the Remote-SSH host component) is downloaded and unpacked
# by the VS Code client on first connection, into ~/.vscode-server/bin/<hash>/.
# That timing is outside our control, so we poll for it in the background and
# install the extension the moment it shows up — no manual "Install in SSH:
# ..." click needed, on transient containers too (they get recreated on every
# workspace switch, which would otherwise wipe ~/.vscode-server each time).
# Runs once per container filesystem lifetime (skips if already installed,
# e.g. after a pause/resume).
# ---------------------------------------------------------------------------
(
  VSIX="/opt/vsix/claude-code.vsix"
  [[ -f "$VSIX" ]] || exit 0
  for _ in $(seq 1 720); do
    CODE_SERVER_BIN=$(find /root/.vscode-server/bin -maxdepth 2 -name code-server -type f 2>/dev/null | head -n1)
    if [[ -n "$CODE_SERVER_BIN" ]]; then
      if ! "$CODE_SERVER_BIN" --list-extensions 2>/dev/null | grep -qi '^anthropic\.claude-code$'; then
        "$CODE_SERVER_BIN" --install-extension "$VSIX" --force >/root/.claude-vsix-install.log 2>&1 || true
      fi
      break
    fi
    sleep 5
  done
) &
disown

exec /usr/sbin/sshd -D
