#!/usr/bin/env bash
set -euo pipefail

# Copy SSH key
if [[ -f /tmp/pubkey/authorized_keys ]]; then
  cp /tmp/pubkey/authorized_keys /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
fi

# Get workspace info from environment (passed by create.sh)
WORKSPACE_PATH="${WORKSPACE_PATH:-/workspace}"
CONTAINER_NAME="${CONTAINER_NAME:-unknown}"
CLAUDE_AUTH_TYPE="${CLAUDE_AUTH_TYPE:-unknown}"

# Write MOTD
cat > /etc/motd <<MOTD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Container: ${CONTAINER_NAME}
  Profile:   claude
  Tool:      Claude Code
  Backend:   Claude API (${CLAUDE_AUTH_TYPE})
MOTD

if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo "  Workspaces:" >> /etc/motd
  IFS=',' read -ra WS_PATHS <<< "$WORKSPACE_PATH"
  for ws in "${WS_PATHS[@]}"; do
    echo "    /workspace/$(basename "$ws")" >> /etc/motd
  done
  WORKSPACE_NAME="$CONTAINER_NAME"
else
  echo "  Workspace: ${WORKSPACE_PATH}" >> /etc/motd
  WORKSPACE_NAME=$(basename "$WORKSPACE_PATH")
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >> /etc/motd

# Configure PS1 to show workspace
echo "export PS1='[\u@${WORKSPACE_NAME}:\w]\\$ '" >> /root/.bashrc
if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo 'cd /workspace' >> /root/.bashrc
else
  echo "cd /workspace/${WORKSPACE_NAME}" >> /root/.bashrc
fi

# Export user-provided environment variables for SSH sessions
# Write all non-system env vars to a file that gets sourced on login
cat > /root/.container_env <<'EOF'
# User-provided environment variables from container-dev env files
# Auto-generated by entrypoint.sh - do not edit manually
EOF

# Export ALL environment variables except system/container internals
# This captures everything from ~/.config/container-dev/env and profile .env files
while IFS='=' read -r -d '' var value; do
  # Skip internal variables set by container runtime and start.sh
  case "$var" in
    WORKSPACE_PATH|CONTAINER_NAME|CLAUDE_AUTH_TYPE|ANTHROPIC_VERTEX_PROJECT_ID|CLOUD_ML_REGION|ANTHROPIC_API_KEY)
      continue ;;
    HOME|PATH|PWD|SHLVL|TERM|HOSTNAME|_)
      continue ;;
    *)
      echo "export ${var}='${value}'" >> /root/.container_env
      ;;
  esac
done < <(env -0)

echo 'source /root/.container_env 2>/dev/null || true' >> /root/.bashrc

# Configure Claude Code settings based on auth type
mkdir -p /root/.claude
case "${CLAUDE_AUTH_TYPE}" in
  vertex)
    cat > /root/.claude/settings.json <<SETTINGS
{
  "theme": "dark",
  "env": {
    "CLAUDE_CODE_USE_VERTEX": "1",
    "ANTHROPIC_VERTEX_PROJECT_ID": "${ANTHROPIC_VERTEX_PROJECT_ID:-}",
    "CLOUD_ML_REGION": "${CLOUD_ML_REGION:-us-central1}"
  }
}
SETTINGS
    ;;
  api)
    cat > /root/.claude/settings.json <<SETTINGS
{
  "theme": "dark",
  "model": "claude-sonnet-4-6",
  "env": {
    "ANTHROPIC_API_KEY": "${ANTHROPIC_API_KEY:-}"
  }
}
SETTINGS
    ;;
  web)
    # OAuth - settings.json created by Claude Code after browser auth
    # Just ensure directory exists; persistent mount handles token
    cat > /root/.claude/settings.json <<SETTINGS
{
  "theme": "dark",
  "model": "claude-sonnet-4-6"
}
SETTINGS
    ;;
  *)
    # Fallback - let Claude Code configure itself
    cat > /root/.claude/settings.json <<SETTINGS
{
  "theme": "dark",
  "model": "claude-sonnet-4-6"
}
SETTINGS
    ;;
esac

exec /usr/sbin/sshd -D
