#!/usr/bin/env bash
set -euo pipefail

# Copy SSH key
if [[ -f /tmp/pubkey/authorized_keys ]]; then
  cp /tmp/pubkey/authorized_keys /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
fi

# Get workspace info from environment (passed by create.sh)
WORKSPACE_PATH="${WORKSPACE_PATH:-/workspace}"
CONTAINER_NAME="${CONTAINER_NAME:-unknown}"
CLINE_PROVIDER="${CLINE_PROVIDER:-anthropic}"

# Write MOTD
cat > /etc/motd <<MOTD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Container: ${CONTAINER_NAME}
  Profile:   cline
  Tool:      Cline
  Provider:  ${CLINE_PROVIDER}
MOTD

if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo "  Workspaces:" >> /etc/motd
  IFS=',' read -ra WS_PATHS <<< "$WORKSPACE_PATH"
  for ws in "${WS_PATHS[@]}"; do
    echo "    /workspace/$(basename "$ws")" >> /etc/motd
  done
  WORKSPACE_NAME="$CONTAINER_NAME"
else
  echo "  Workspace: ${WORKSPACE_PATH}" >> /etc/motd
  WORKSPACE_NAME=$(basename "$WORKSPACE_PATH")
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >> /etc/motd

# Configure PS1 to show workspace
echo "export PS1='[\u@${WORKSPACE_NAME}:\w]\\$ '" >> /root/.bashrc
echo "export AI_SDK_LOG_WARNINGS=false" >> /root/.bashrc
if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo 'cd /workspace' >> /root/.bashrc
else
  echo "cd /workspace/${WORKSPACE_NAME}" >> /root/.bashrc
fi

# Export user-provided environment variables for SSH sessions
# Write all non-system env vars to a file that gets sourced on login.
# sshd scrubs the runtime environment so auth vars (ANTHROPIC_API_KEY,
# ANTHROPIC_VERTEX_PROJECT_ID, etc.) must be persisted here to be visible
# in interactive login shells.
cat > /root/.container_env <<'EOF'
# User-provided environment variables from container-dev env files
# Auto-generated by entrypoint.sh - do not edit manually
EOF

while IFS='=' read -r -d '' var value; do
  case "$var" in
    WORKSPACE_PATH|CONTAINER_NAME)
      continue ;;
    HOME|PATH|PWD|SHLVL|TERM|HOSTNAME|_)
      continue ;;
    *)
      echo "export ${var}='${value}'" >> /root/.container_env
      ;;
  esac
done < <(env -0)

echo 'source /root/.container_env 2>/dev/null || true' >> /root/.bashrc

# ---------------------------------------------------------------------------
# Cline config seeding
#
# Host config directory is bind-mounted read-only at /tmp/cline-host by
# create.sh. On each interactive login we re-seed ~/.cline/data/ from it so
# host edits take effect on the next cline launch without recreating the
# container.
#
# Provider name → Cline internal apiProvider mapping:
#   anthropic → anthropic   (direct Anthropic API key)
#   mini4 (or any other name) → openai   (OpenAI-compat LAN server; needs openai.json)
#
# Both anthropic and openai-compat credential blocks are always written when
# their config is present, so the VS Code extension's provider picker works
# immediately without re-login.
#
# NOTE: use `cat >dest` not `cp` — base .bashrc aliases `cp` to `cp -i`
# which prompts interactively and hangs SSH logins.
# ---------------------------------------------------------------------------

_seed_cline_config() {
  local host_dir="/tmp/cline-host"
  local data_dir="/root/.cline/data"
  mkdir -p "$data_dir"

  # Determine default provider
  local provider="anthropic"
  if [[ -f "$host_dir/provider" ]]; then
    provider=$(cat "$host_dir/provider")
  fi

  # Map container-dev provider name → Cline internal apiProvider value
  # anthropic → anthropic (direct API key)
  # anything else (e.g. mini4) → openai (OpenAI-compat LAN server)
  local cline_api_provider
  case "$provider" in
    anthropic) cline_api_provider="anthropic" ;;
    *)         cline_api_provider="openai" ;;
  esac

  # Build globalState.json base
  local global_state
  global_state=$(jq -n \
    --arg provider "$cline_api_provider" \
    '{
      "apiProvider":         $provider,
      "planModeApiProvider": $provider,
      "actModeApiProvider":  $provider,
      "anthropicModelId":    "claude-sonnet-4-6"
    }'
  )

  # --- OpenAI-compat fields (any non-anthropic provider) ---
  if [[ "$cline_api_provider" == "openai" && -f "$host_dir/openai.json" ]]; then
    local base_url model_id context_window supports_images
    base_url=$(jq -r '.baseUrl       // empty' "$host_dir/openai.json" 2>/dev/null)
    model_id=$(jq -r '.modelId       // empty' "$host_dir/openai.json" 2>/dev/null)
    context_window=$(jq -r '.contextWindow // 8192' "$host_dir/openai.json" 2>/dev/null)
    supports_images=$(jq -r '.supportsImages // false' "$host_dir/openai.json" 2>/dev/null)

    if [[ -n "$base_url" ]]; then
      global_state=$(echo "$global_state" | jq \
        --arg url   "$base_url" \
        --arg model "${model_id:-}" \
        --argjson ctx  "$context_window" \
        --argjson imgs "$supports_images" \
        '. + {
          "openAiBaseUrl":  $url,
          "openAiModelId":  $model,
          "openAiCustomModelInfo": {
            "maxTokens":            8192,
            "contextWindow":        $ctx,
            "supportsImages":       $imgs,
            "supportsComputerUse":  false,
            "supportsPromptCache":  false,
            "inputPrice":           0,
            "outputPrice":          0
          }
        }'
      )
    fi
  fi

  echo "$global_state" > "$data_dir/globalState.json"

  # --- secrets.json ---
  # Anthropic: API key from env. OpenAI-compat: placeholder key.
  # Vertex: nothing — auth is via Google ADC, not a stored secret.
  local secrets='{}'
  if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
    secrets=$(echo "$secrets" | jq --arg key "$ANTHROPIC_API_KEY" \
      '. + {"anthropicApiKey": $key}')
  fi
  if [[ -f "$host_dir/openai.json" ]]; then
    local openai_key
    openai_key=$(jq -r '.apiKey // "sk-local"' "$host_dir/openai.json" 2>/dev/null)
    secrets=$(echo "$secrets" | jq --arg key "$openai_key" \
      '. + {"openAiApiKey": $key}')
  fi

  echo "$secrets" > "$data_dir/secrets.json"
}

# Seed config at container start
_seed_cline_config

# ---------------------------------------------------------------------------
# Auto-install the baked-in Cline VS Code extension
#
# VS Code Server (the Remote-SSH host component) is downloaded and unpacked
# by the VS Code client on first connection, into ~/.vscode-server/bin/<hash>/.
# That timing is outside our control, so we poll for it in the background
# and install the extension the moment it shows up — no manual "Install in
# SSH: ..." click needed. Runs once per container filesystem lifetime (skips
# if already installed, e.g. after a pause/resume).
# ---------------------------------------------------------------------------
(
  VSIX="/opt/vsix/cline.vsix"
  [[ -f "$VSIX" ]] || exit 0
  for _ in $(seq 1 720); do
    CODE_SERVER_BIN=$(find /root/.vscode-server/bin -maxdepth 2 -name code-server -type f 2>/dev/null | head -n1)
    if [[ -n "$CODE_SERVER_BIN" ]]; then
      if ! "$CODE_SERVER_BIN" --list-extensions 2>/dev/null | grep -qi '^saoudrizwan\.claude-dev$'; then
        "$CODE_SERVER_BIN" --install-extension "$VSIX" --force >/root/.cline-vsix-install.log 2>&1 || true
      fi
      break
    fi
    sleep 5
  done
) &
disown

# Re-seed on every interactive login so host edits take effect next cline launch
cat >> /root/.bashrc <<'BASHRC'
if [[ -d /tmp/cline-host ]]; then
  _seed_cline_config() {
    local host_dir="/tmp/cline-host"
    local data_dir="/root/.cline/data"
    mkdir -p "$data_dir"

    local provider="anthropic"
    if [[ -f "$host_dir/provider" ]]; then
      provider=$(cat "$host_dir/provider")
    fi

    local cline_api_provider
    case "$provider" in
      anthropic) cline_api_provider="anthropic" ;;
      *)         cline_api_provider="openai" ;;
    esac

    local global_state
    global_state=$(jq -n \
      --arg provider "$cline_api_provider" \
      '{
        "apiProvider":         $provider,
        "planModeApiProvider": $provider,
        "actModeApiProvider":  $provider,
        "anthropicModelId":    "claude-sonnet-4-6"
      }'
    )

    if [[ "$cline_api_provider" == "openai" && -f "$host_dir/openai.json" ]]; then
      local base_url model_id context_window supports_images
      base_url=$(jq -r '.baseUrl        // empty' "$host_dir/openai.json" 2>/dev/null)
      model_id=$(jq -r '.modelId        // empty' "$host_dir/openai.json" 2>/dev/null)
      context_window=$(jq -r '.contextWindow // 8192' "$host_dir/openai.json" 2>/dev/null)
      supports_images=$(jq -r '.supportsImages // false' "$host_dir/openai.json" 2>/dev/null)

      if [[ -n "$base_url" ]]; then
        global_state=$(echo "$global_state" | jq \
          --arg url   "$base_url" \
          --arg model "${model_id:-}" \
          --argjson ctx  "$context_window" \
          --argjson imgs "$supports_images" \
          '. + {
            "openAiBaseUrl":  $url,
            "openAiModelId":  $model,
            "openAiCustomModelInfo": {
              "maxTokens":           8192,
              "contextWindow":       $ctx,
              "supportsImages":      $imgs,
              "supportsComputerUse": false,
              "supportsPromptCache": false,
              "inputPrice":          0,
              "outputPrice":         0
            }
          }'
        )
      fi
    fi

    echo "$global_state" > "$data_dir/globalState.json"

    local secrets='{}'
    if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
      secrets=$(echo "$secrets" | jq --arg key "$ANTHROPIC_API_KEY" \
        '. + {"anthropicApiKey": $key}')
    fi
    if [[ -f "$host_dir/openai.json" ]]; then
      local openai_key
      openai_key=$(jq -r '.apiKey // "sk-local"' "$host_dir/openai.json" 2>/dev/null)
      secrets=$(echo "$secrets" | jq --arg key "$openai_key" \
        '. + {"openAiApiKey": $key}')
    fi

    echo "$secrets" > "$data_dir/secrets.json"
  }
  _seed_cline_config
fi
BASHRC

exec /usr/sbin/sshd -D
