#!/usr/bin/env bash
set -euo pipefail

# Copy SSH key
if [[ -f /tmp/pubkey/authorized_keys ]]; then
  cp /tmp/pubkey/authorized_keys /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
fi

# Get workspace info from environment (passed by create.sh)
WORKSPACE_PATH="${WORKSPACE_PATH:-/workspace}"
CONTAINER_NAME="${CONTAINER_NAME:-unknown}"
CLINE_PROVIDER="${CLINE_PROVIDER:-anthropic}"

# Write MOTD
cat > /etc/motd <<MOTD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Container: ${CONTAINER_NAME}
  Profile:   cline
  Tool:      Cline
  Provider:  ${CLINE_PROVIDER}
MOTD

if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo "  Workspaces:" >> /etc/motd
  IFS=',' read -ra WS_PATHS <<< "$WORKSPACE_PATH"
  for ws in "${WS_PATHS[@]}"; do
    echo "    /workspace/$(basename "$ws")" >> /etc/motd
  done
  WORKSPACE_NAME="$CONTAINER_NAME"
else
  echo "  Workspace: ${WORKSPACE_PATH}" >> /etc/motd
  WORKSPACE_NAME=$(basename "$WORKSPACE_PATH")
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >> /etc/motd

# Configure PS1 to show workspace
echo "export PS1='[\u@${WORKSPACE_NAME}:\w]\\$ '" >> /root/.bashrc
echo "export AI_SDK_LOG_WARNINGS=false" >> /root/.bashrc
if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo 'cd /workspace' >> /root/.bashrc
else
  echo "cd /workspace/${WORKSPACE_NAME}" >> /root/.bashrc
fi

# Export user-provided environment variables for SSH sessions
# Write all non-system env vars to a file that gets sourced on login
cat > /root/.container_env <<'EOF'
# User-provided environment variables from container-dev env files
# Auto-generated by entrypoint.sh - do not edit manually
EOF

# Export ALL environment variables except system/container internals
# sshd scrubs the runtime environment, so auth vars must be persisted here
# to be visible to interactive login shells and cline launched from them.
while IFS='=' read -r -d '' var value; do
  case "$var" in
    WORKSPACE_PATH|CONTAINER_NAME)
      continue ;;
    HOME|PATH|PWD|SHLVL|TERM|HOSTNAME|_)
      continue ;;
    *)
      echo "export ${var}='${value}'" >> /root/.container_env
      ;;
  esac
done < <(env -0)

echo 'source /root/.container_env 2>/dev/null || true' >> /root/.bashrc

# ---------------------------------------------------------------------------
# Cline config seeding
#
# Host config directory is bind-mounted read-only at /tmp/cline-host by
# create.sh. On each interactive login we re-seed ~/.cline/data/ from it so
# host edits take effect on the next cline launch without recreating the
# container.
#
# Provider name mapping (container-dev name → Cline internal apiProvider):
#   anthropic → anthropic
#   mini4     → openai  (OpenAI-compat; Cline's name for this provider type)
#
# Both provider credential blocks are always written when host config is
# present, so the VS Code extension's provider picker works immediately.
#
# NOTE: use `cat >dest` not `cp` — base .bashrc aliases `cp` to `cp -i`
# which prompts interactively and hangs SSH logins.
# ---------------------------------------------------------------------------

_seed_cline_config() {
  local host_dir="/tmp/cline-host"
  local data_dir="/root/.cline/data"
  mkdir -p "$data_dir"

  # Determine default provider (container-dev name)
  local provider="anthropic"
  if [[ -f "$host_dir/provider" ]]; then
    provider=$(cat "$host_dir/provider")
  fi

  # Map container-dev provider name → Cline internal apiProvider value
  local cline_api_provider
  case "$provider" in
    anthropic) cline_api_provider="anthropic" ;;
    mini4)     cline_api_provider="openai" ;;
    *)         cline_api_provider="$provider" ;;
  esac

  # Build globalState.json base
  local global_state
  global_state=$(jq -n \
    --arg provider "$cline_api_provider" \
    '{"apiProvider": $provider, "anthropicModelId": "claude-sonnet-4-6"}'
  )

  # Merge OpenAI-compat fields if openai.json exists on host
  if [[ -f "$host_dir/openai.json" ]]; then
    local base_url model_id context_window supports_images
    base_url=$(jq -r '.baseUrl // empty' "$host_dir/openai.json" 2>/dev/null)
    model_id=$(jq -r '.modelId // empty' "$host_dir/openai.json" 2>/dev/null)
    context_window=$(jq -r '.contextWindow // 8192' "$host_dir/openai.json" 2>/dev/null)
    supports_images=$(jq -r '.supportsImages // false' "$host_dir/openai.json" 2>/dev/null)

    if [[ -n "$base_url" ]]; then
      global_state=$(echo "$global_state" | jq \
        --arg url "$base_url" \
        --arg model "${model_id:-}" \
        --argjson ctx "$context_window" \
        --argjson imgs "$supports_images" \
        '. + {
          "openAiBaseUrl": $url,
          "openAiModelId": $model,
          "openAiCustomModelInfo": {
            "maxTokens": 8192,
            "contextWindow": $ctx,
            "supportsImages": $imgs,
            "supportsComputerUse": false,
            "supportsPromptCache": false,
            "inputPrice": 0,
            "outputPrice": 0
          }
        }'
      )
    fi
  fi

  echo "$global_state" > "$data_dir/globalState.json"

  # Build secrets.json — write API key from env; placeholder for openai-compat
  local secrets='{}'
  if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
    secrets=$(echo "$secrets" | jq --arg key "$ANTHROPIC_API_KEY" \
      '. + {"anthropicApiKey": $key}')
  fi
  if [[ -f "$host_dir/openai.json" ]]; then
    local openai_key
    openai_key=$(jq -r '.apiKey // "sk-local"' "$host_dir/openai.json" 2>/dev/null)
    secrets=$(echo "$secrets" | jq --arg key "$openai_key" \
      '. + {"openAiApiKey": $key}')
  fi

  echo "$secrets" > "$data_dir/secrets.json"
}

# Seed config at container start
_seed_cline_config

# Re-seed on every interactive login so host edits take effect next cline launch
cat >> /root/.bashrc <<'BASHRC'
if [[ -d /tmp/cline-host ]]; then
  _seed_cline_config() {
    local host_dir="/tmp/cline-host"
    local data_dir="/root/.cline/data"
    mkdir -p "$data_dir"

    local provider="anthropic"
    if [[ -f "$host_dir/provider" ]]; then
      provider=$(cat "$host_dir/provider")
    fi

    local cline_api_provider
    case "$provider" in
      anthropic) cline_api_provider="anthropic" ;;
      mini4)     cline_api_provider="openai" ;;
      *)         cline_api_provider="$provider" ;;
    esac

    local global_state
    global_state=$(jq -n \
      --arg provider "$cline_api_provider" \
      '{"apiProvider": $provider, "anthropicModelId": "claude-sonnet-4-6"}'
    )

    if [[ -f "$host_dir/openai.json" ]]; then
      local base_url model_id context_window supports_images
      base_url=$(jq -r '.baseUrl // empty' "$host_dir/openai.json" 2>/dev/null)
      model_id=$(jq -r '.modelId // empty' "$host_dir/openai.json" 2>/dev/null)
      context_window=$(jq -r '.contextWindow // 8192' "$host_dir/openai.json" 2>/dev/null)
      supports_images=$(jq -r '.supportsImages // false' "$host_dir/openai.json" 2>/dev/null)

      if [[ -n "$base_url" ]]; then
        global_state=$(echo "$global_state" | jq \
          --arg url "$base_url" \
          --arg model "${model_id:-}" \
          --argjson ctx "$context_window" \
          --argjson imgs "$supports_images" \
          '. + {
            "openAiBaseUrl": $url,
            "openAiModelId": $model,
            "openAiCustomModelInfo": {
              "maxTokens": 8192,
              "contextWindow": $ctx,
              "supportsImages": $imgs,
              "supportsComputerUse": false,
              "supportsPromptCache": false,
              "inputPrice": 0,
              "outputPrice": 0
            }
          }'
        )
      fi
    fi

    echo "$global_state" > "$data_dir/globalState.json"

    local secrets='{}'
    if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
      secrets=$(echo "$secrets" | jq --arg key "$ANTHROPIC_API_KEY" \
        '. + {"anthropicApiKey": $key}')
    fi
    if [[ -f "$host_dir/openai.json" ]]; then
      local openai_key
      openai_key=$(jq -r '.apiKey // "sk-local"' "$host_dir/openai.json" 2>/dev/null)
      secrets=$(echo "$secrets" | jq --arg key "$openai_key" \
        '. + {"openAiApiKey": $key}')
    fi

    echo "$secrets" > "$data_dir/secrets.json"
  }
  _seed_cline_config
fi
BASHRC

exec /usr/sbin/sshd -D
