#!/usr/bin/env bash
set -euo pipefail

# Copy SSH key
if [[ -f /tmp/pubkey/authorized_keys ]]; then
  cp /tmp/pubkey/authorized_keys /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
fi

# Codex state is bind-mounted by create.sh. The default is deliberately the
# same path used by the official CLI and IDE extension.
export CODEX_HOME="${CODEX_HOME:-/root/.codex}"
mkdir -p "$CODEX_HOME"
chmod 700 "$CODEX_HOME" 2>/dev/null || true

WORKSPACE_PATH="${WORKSPACE_PATH:-/workspace}"
CONTAINER_NAME="${CONTAINER_NAME:-unknown}"
CODEX_AUTH_TYPE="${CODEX_AUTH_TYPE:-unknown}"
CODEX_AUTH_STATE="$CODEX_AUTH_TYPE"

# A host-side auth.json is the portable form of Codex's cached login. A
# macOS keychain is not available inside the Linux container, so if no file is
# mounted, bootstrap from an explicitly supplied token when one is present.
if [[ -f "$CODEX_HOME/auth.json" ]]; then
  CODEX_AUTH_STATE="cached"
elif codex login status >/dev/null 2>&1; then
  CODEX_AUTH_STATE="cached"
elif [[ -n "${CODEX_ACCESS_TOKEN:-}" ]]; then
  if printf '%s' "$CODEX_ACCESS_TOKEN" | codex login --with-access-token \
      >"$CODEX_HOME/codex-login.log" 2>&1; then
    CODEX_AUTH_STATE="access-token"
  else
    CODEX_AUTH_STATE="login-failed"
  fi
elif [[ -n "${OPENAI_API_KEY:-}" ]]; then
  if printf '%s' "$OPENAI_API_KEY" | codex login --with-api-key \
      >"$CODEX_HOME/codex-login.log" 2>&1; then
    CODEX_AUTH_STATE="api-key"
  else
    CODEX_AUTH_STATE="login-failed"
  fi
else
  CODEX_AUTH_STATE="setup-required"
fi

# Write MOTD
cat > /etc/motd <<MOTD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Container: ${CONTAINER_NAME}
  Profile:   codex
  Tool:      OpenAI Codex CLI
  Auth:      ${CODEX_AUTH_STATE}
MOTD

if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo "  Workspaces:" >> /etc/motd
  IFS=',' read -ra WS_PATHS <<< "$WORKSPACE_PATH"
  for ws in "${WS_PATHS[@]}"; do
    echo "    /workspace/$(basename "$ws")" >> /etc/motd
  done
  WORKSPACE_NAME="$CONTAINER_NAME"
else
  echo "  Workspace: ${WORKSPACE_PATH}" >> /etc/motd
  WORKSPACE_NAME=$(basename "$WORKSPACE_PATH")
fi

if [[ "$CODEX_AUTH_STATE" == "setup-required" ]]; then
  cat >> /etc/motd <<'MOTD'
  Run: codex login --device-auth
MOTD
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >> /etc/motd

# Configure PS1 to show workspace
echo "export PS1='[\u@${WORKSPACE_NAME}:\w]\\$ '" >> /root/.bashrc
if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo 'cd /workspace' >> /root/.bashrc
else
  echo "cd /workspace/${WORKSPACE_NAME}" >> /root/.bashrc
fi

# Export user-provided environment variables for SSH sessions. This follows
# the existing Claude profile convention so API-key auth also works after sshd
# has scrubbed the container runtime environment.
cat > /root/.container_env <<'EOF'
# User-provided environment variables from container-dev env files
# Auto-generated by entrypoint.sh - do not edit manually
EOF

while IFS='=' read -r -d '' var value; do
  case "$var" in
    WORKSPACE_PATH|CONTAINER_NAME)
      continue ;;
    HOME|PATH|PWD|SHLVL|TERM|HOSTNAME|_)
      continue ;;
    *)
      echo "export ${var}='${value}'" >> /root/.container_env
      ;;
  esac
done < <(env -0)

echo 'source /root/.container_env 2>/dev/null || true' >> /root/.bashrc

# Auto-install the baked-in Codex extension once VS Code Server appears after
# the first Remote-SSH connection.
(
  VSIX="/opt/vsix/codex.vsix"
  [[ -f "$VSIX" ]] || exit 0
  for _ in $(seq 1 720); do
    CODE_SERVER_BIN=$(find /root/.vscode-server/bin -maxdepth 2 -name code-server -type f 2>/dev/null | head -n1)
    if [[ -n "$CODE_SERVER_BIN" ]]; then
      if ! "$CODE_SERVER_BIN" --list-extensions 2>/dev/null | grep -qi '^openai\.chatgpt$'; then
        "$CODE_SERVER_BIN" --install-extension "$VSIX" --force >/root/.codex-vsix-install.log 2>&1 || true
      fi
      break
    fi
    sleep 5
  done
) &
disown

exec /usr/sbin/sshd -D
