#!/usr/bin/env bash
set -euo pipefail

# Copy SSH key
if [[ -f /tmp/pubkey/authorized_keys ]]; then
  cp /tmp/pubkey/authorized_keys /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
fi

WORKSPACE_PATH="${WORKSPACE_PATH:-/workspace}"
CONTAINER_NAME="${CONTAINER_NAME:-unknown}"

# Write MOTD
cat > /etc/motd <<MOTD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Container: ${CONTAINER_NAME}
  Profile:   opencode
  Tool:      OpenCode
MOTD

if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo "  Workspaces:" >> /etc/motd
  IFS=',' read -ra WS_PATHS <<< "$WORKSPACE_PATH"
  for ws in "${WS_PATHS[@]}"; do
    echo "    /workspace/$(basename "$ws")" >> /etc/motd
  done
  WORKSPACE_NAME="$CONTAINER_NAME"
else
  echo "  Workspace: ${WORKSPACE_PATH}" >> /etc/motd
  WORKSPACE_NAME=$(basename "$WORKSPACE_PATH")
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >> /etc/motd

# Configure PS1 to show workspace
echo "export PS1='[\u@${WORKSPACE_NAME}:\w]\\$ '" >> /root/.bashrc
if [[ "$WORKSPACE_PATH" == *,* ]]; then
  echo 'cd /workspace' >> /root/.bashrc
else
  echo "cd /workspace/${WORKSPACE_NAME}" >> /root/.bashrc
fi

# Export user-provided environment variables for SSH sessions
# sshd scrubs the runtime environment so auth vars (ANTHROPIC_API_KEY, etc.)
# must be persisted here to be visible in interactive login shells.
cat > /root/.container_env <<'EOF'
# User-provided environment variables from container-dev env files
# Auto-generated by entrypoint.sh - do not edit manually
EOF

while IFS='=' read -r -d '' var value; do
  case "$var" in
    WORKSPACE_PATH|CONTAINER_NAME)
      continue ;;
    HOME|PATH|PWD|SHLVL|TERM|HOSTNAME|_)
      continue ;;
    *)
      echo "export ${var}='${value}'" >> /root/.container_env
      ;;
  esac
done < <(env -0)

echo 'source /root/.container_env 2>/dev/null || true' >> /root/.bashrc

# ---------------------------------------------------------------------------
# OpenCode config seeding
#
# OpenCode reads its global config from ~/.config/opencode/opencode.json. We
# seed a default model + Anthropic provider entry that pulls the API key from
# ANTHROPIC_API_KEY via opencode's {env:...} substitution, so no key ever
# needs to be written to disk. Only written if missing, so a workspace-local
# opencode.json (or manual edits to this file) are never clobbered.
# ---------------------------------------------------------------------------
OPENCODE_CONFIG="/root/.config/opencode/opencode.json"
if [[ ! -f "$OPENCODE_CONFIG" ]]; then
  mkdir -p "$(dirname "$OPENCODE_CONFIG")"
  cat > "$OPENCODE_CONFIG" <<'CONFIG'
{
  "$schema": "https://opencode.ai/config.json",
  "model": "anthropic/claude-sonnet-4-5",
  "provider": {
    "anthropic": {
      "options": {
        "apiKey": "{env:ANTHROPIC_API_KEY}"
      }
    }
  }
}
CONFIG
fi

exec /usr/sbin/sshd -D
